### ISSUE TITLE
OSError: truncated file

### ISSUE THREAD

**Issue by ChiaraF32** [Illumina/SMNCopyNumberCaller#6]
Hi! 

Loving this program so far, which I have been successfully able to run on some data.

I just tried running it on another bam file however, and I got the following error output:

```
INFO:root:Processing sample D17_0442.hg38 at 2022-08-02 05:38:10.924313
[W::hts_idx_load2] The index file is older than the data file: /data/preprocessed/sma/D17_0442.hg38.bai
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
Traceback (most recent call last):
  File "./smn_caller.py", line 298, in <module>
    main()
  File "./smn_caller.py", line 275, in main
    reference_fasta,
  File "./smn_caller.py", line 111, in smn_cn_caller
    bam, region_dic, threads, reference=reference_fasta, gc_correct=False
  File "/data/SMNCopyNumberCaller/depth_calling/bin_count.py", line 41, in get_normed_depth
    bamf, region_dic, nCores, reference
  File "/data/SMNCopyNumberCaller/depth_calling/bin_count.py", line 188, in count_reads_and_prepare_for_normalization
    region_reads = get_read_count(bamfile, region)
  File "/data/SMNCopyNumberCaller/depth_calling/bin_count.py", line 106, in get_read_count
    for read in reads:
  File "pysam/libcalignmentfile.pyx", line 2094, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
```

This was my run script and manifest, for reference
```
./smn_caller.py --manifest manifest.txt \
              --genome 38 \
              --reference /data/references/Homo_sapiens_assembly38.fasta \
              --prefix D17-0442_SMN \
              --outDir ./results \
              --threads 10
```
```
/data/preprocessed/sma/D17_0442.hg38.bam
```
Is this an indication that there is an issue with this data?

Cheers,
Chiara

**Comment by xiao-chen-xc** [comment]
Hi Chiara, looks like the bam file is a truncated file. I'd suggest that you try generating that bam file again.

**Comment by ChiaraF32** [comment]
Thanks, I re-generated the file and it worked well.
